### ISSUE TITLE
@types/node version doesn't match documented min supported Node version

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5997]
Our main docs page https://fluidframework.com/start/quick-start/ says Fluid supports 12.17 and later. But we are importing @types/node v 12.19 (see #5796) so we could quietly introduce a dependency on a 12.19 feature new since 12.17. I haven't looked at the release notes to know what that delta is like, but IMO we should keep these two versions in sync. 

cc @curtisman @tylerbutler @DLehenbauer

**Comment by tylerbutler** [comment]
I don't think this is a practical concern for 12.17 vs 12.19, but I agree that being explicit and consistent about these deps.

**Comment by markfields** [comment]
@tylerbutler @DLehenbauer - that PR addresses yet another place the Node version comes into play, namely what version is actually installed. I should have called that out in the issue, but nevertheless the original point of this issue isn't addressed here. 

I'm ok if we punt on it (or leave this issue closed) but wanted to be clear.

I think a proper "fix" here would involve some policy checks to compare the @types/node version with the actual node version (maybe just emit a warning, with an auto fix option?), and also keep an eye on the version called out on the docs site.

**Comment by DLehenbauer** [comment]
I see your point that we're still not strictly synchronized, but I think we've at least improved:

* We recommend user's install the latest 12.x release
* Minor node revisions are non-breaking (i.e., don't remove APIs).

Code that compiles should also run.  Developers who want to introduce usage of new APIs can bump '@types/node' as needed.

No objection if you want to reopen, but going further feels like diminishing returns to me.

**Comment by markfields** [comment]
@tylerbutler can we update the docs to say Fluid requires/recommends the latest LTS of v12?

**Comment by tylerbutler** [comment]
@markfields We did say that at some point in the past, but when the (very unusual) change had to be made to depend on something 12.17+, we snapped to that version and updated the docs to say that.

I think the general statement is that you should use the latest 12.x version available, but you MUST use at least 12.17 since we have a hard dependency on it. And then be explicit about what version our CI uses so people know what we're running our tests on, but I am pretty sure that's also "latest 12.x".

To Daniel's point, node doesn't introduce breaking changes in minor versions, so if 12.23.0 (12.22.1 is the latest as of this writing)  is released tomorrow and someone installs it, I would expect our code to build and run.

Applying that logic to the @types package, then it _is_ possible for something to "break" TS compilation because the node typings had a bug or something. But I think that's true of all packages that don't include typings.

If we really want to lock this down, we would need to stop using caret (`^`) dependencies for the @types packages and pin them to a precise version, or _always_ use `npm ci`, but IMO that's more overhead than valuable.

**Comment by markfields** [comment]
Totally agree with all that. But what about the case where someone has NOT updated past 12.17 (and we claim to support that configuration) but then we perhaps inadvertently introduce a dependency on 12.19+? This is what I'm trying to mitigate.

Granted, most people shouldn't be in this situation for the exact reason you brought up about minor version bumps - it's safe to minor bump a dependency without changing their code.  I'd just rather make the little tweak to the wording and not say we are compatible specifically with 12.17.

**Comment by markfields** [comment]
In other words, "non-breaking" only applies one-way. But this may only matter for Server? For client bits, not sure how the node dependencies come into play relative to different webpacked bundles, etc.

**Comment by markfields** [comment]
Anyway, feel free to close after all, just wanted to communicate my point better.

I still think the cleanest solution is to bump the documented min supported version whenever we update the @types/node package (which can be less frequent than minor bumps of the real dependency), and that aside I want us to rightly set expectations in the docs about supported configurations. Is it more complex than just stating a min supported version? Maybe so but consensus is that it's not worth being so pedantic? 

Anyhow, I'll not push on it further. And now I'm disabling GitHub notifications while on leave... 🙈
